browser=chrome
url=https://mmukessh-trials80.orangehrmlive.com
username=admin
password=YsyE3U7@Dg

invaliusername=mnimda
invalidpassword=fhgfgf55

blankusername=
blankpassword=

profileImage=src/main/resources/profile.jpg
